language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: o9oGKzDvmlvK4F8sxTmGXk5ltHyRukXf4FkFihv2fVB3+ucNQUuF2GXeCKZ9oU77+EjFFdilbGfOtq4jfWP7LjQsioNyQYMt2g+ptKOh45mWdY0raXprJqhAIVBLw9+CQ3grWLoMCT/Nkiim+gmiXz6pH6XBquf0sLapdAcBmF0cQoQaZJDCRQr3wZhBx1csa6f60jsiz1cO9+RTpIFLDvXMXn3KoSVflT6e2qaNDKUwNCh225Vybvx1PGErltVFbTyJv/AEI1GxkYZ89TbUlAlUTZszJw9JsATHop/GlVy1y/HZeeYnsko1Y/BwzzyX0s9rMJDs7a/8JyZlJbsJ22flD0xSVALzrQP2sOyV7sC7C9spaCkOTdFHdgDhlLXEi0QYICAW51ydLtgBNAx5wCOMvhQbrrn/hNU5mCD0EfeOx90xEjiQdLW7oahD1e+QTdMIqwAa4oAjhwtAAnDnwMUDmu2+hb43pd7e89xRvaALKisq7CF+xyuAZckpKakhYIzxXUYWyPpzC59sdzDbMXew6Bwl3TaoWq4kXp+Gv+pFq9D7p+rSXKITm//yENuFqTOC7TICzjSIgz1mQswBBxcEAsoerjIg4u8Lf8SBdJvHTwbCHSjjPamuo1MQ3w8Pnst12wMgDlvLcILNZl6ezble37QR8ovA65+KUVsYoYQ=
  app: whispering-basin-37950
  on:
    repo: jnintal/node-shopping-list-integration-tests
